#include "../../runtimes/php/Dockerfile"

FROM runtime
ARG PHPQA_DOCKER_IMAGE
ENV PHPQA_DOCKER_IMAGE=${PHPQA_DOCKER_IMAGE}
ENV GENERATOR=php
COPY generators/php/bin/ /opt/openapi-generator/generator/bin
COPY generators/php/config/ /opt/openapi-generator/generator/config
COPY generators/php/overwrite/ /opt/openapi-generator/generator/overwrite
COPY generators/php/templates/ /opt/openapi-generator/generator/templates
