ARG PHPQA_DOCKER_IMAGE=jakzal/phpqa:1.108.1-php8.3-alpine

#include "../../Dockerfile"

FROM ${PHPQA_DOCKER_IMAGE} AS builder

FROM generator AS runtime
RUN apk add --no-cache \
        php83-cli \
        php83-ctype \
        php83-curl \
        php83-dom \
        php83-iconv \
        php83-json \
        php83-mbstring \
        php83-openssl \
        php83-phar \
        php83-simplexml \
        php83-tokenizer \
        php83-xml \
        php83-xmlwriter
COPY --from=builder /tools /tools
ENV COMPOSER_HOME=/tools/.composer
