ARG PHPQA_DOCKER_IMAGE=jakzal/phpqa:1.91.0-alpine

#include "../../Dockerfile"

FROM ${PHPQA_DOCKER_IMAGE} AS builder

FROM generator AS runtime
RUN apk add --no-cache \
        php82-cli \
        php82-curl \
        php82-dom \
        php82-iconv \
        php82-json \
        php82-mbstring \
        php82-openssl \
        php82-phar \
        php82-simplexml \
        php82-tokenizer \
        php82-xml \
        php82-xmlwriter \
    && ln -s /usr/bin/php82 /usr/bin/php
COPY --from=builder /tools /tools
ENV COMPOSER_HOME=/tools/.composer
